<div class="center bold title">Create a New Game</div>
<div class="center subtitle">Fill the form to create a new Game. </div>
<div class="center subtitle">Fields marked with a star (*) are mandatory</div>
<br/>
<?php 
$message = "";
if(0 < strlen($this->message))
{
	$class = $this->success? 'success' : 'failed';
	$message = '<div class="title bold '.$class.'">'.$this->message.'</div>';
}
echo $message;
echo $this->form;